##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_arith

SRC = arith_theorem_producer_old.cpp \
 arith_theorem_producer.cpp \
 theory_arith.cpp \
 theory_arith_old.cpp \
 theory_arith_new.cpp

HEADERS = arith_proof_rules.h \
 arith_theorem_producer_old.h \
 arith_theorem_producer.h \
 arith_exception.h

LIBRARY=libtheory_arith.a

include ../../Makefile.local
